name: e2e
on:
  workflow_call:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm start
          wait-on: "http://localhost:3000"
          config-file: cypress/config/dev.config.ts
  deploy-staging:
    needs: cypress-run
    if: ${{ !contains(github.ref, 'main') }}
    uses: ./.github/workflows/deploy_staging.yml
    secrets: inherit
