name: Lint
on:
  - push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - uses: pnpm/action-setup@v4
          with:
            version: 9.6.0

        - name: ESLint
          run: pnpm eslint-only