name: Main
on:
  - push
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  e2e:
    uses: ./.github/workflows/e2e.yml
  deploy-staging:
    needs:
      - lint
      - e2e
    if: ${{ !contains(github.ref, 'main') }}
    uses: ./.github/workflows/deploy_staging.yml
    secrets: inherit
  deploy-prod:
    needs:
      - lint
      - e2e
    if: ${{ contains(github.ref, 'main') }}
    uses: ./.github/workflows/deploy_prod.yml
    secrets: inherit
